index:
    path: /
    controller: App\Controller\DefaultController::index

article:
    path: /article/{id}
    controller: App\Controller\DefaultController::article
    defaults:
        id: 1
    requirements:
        id: '\d+'
